# ─── Bracket Data ───────────────────────────────────────────────────────────
# Auto-generated by generate_bracket_data.py on Selection Sunday.
# Do not edit manually — re-run the script to regenerate.

BRACKET_LOCKED = True

# ── Simulation metadata ───────────────────────────────────────────────────────
SIM_META = {
    "n_trials": 10000,
    "runtime_sec": 3.1,
    "model": "Formula-based log5",
    "season": "2025–26 NCAA Tournament",
}

# ── Round-by-round probabilities ─────────────────────────────────────────────
SIM_DATA = [
    {
        "team": "Duke",
        "region": "East",
        "seed": 1,
        "R32": 0.9975,
        "S16": 0.9247,
        "E8": 0.8158,
        "F4": 0.6884,
        "Champion": 0.2829,
    },
    {
        "team": "Michigan",
        "region": "Midwest",
        "seed": 1,
        "R32": 0.9975,
        "S16": 0.9324,
        "E8": 0.7855,
        "F4": 0.5977,
        "Champion": 0.2126,
    },
    {
        "team": "Arizona",
        "region": "West",
        "seed": 1,
        "R32": 0.9983,
        "S16": 0.916,
        "E8": 0.7736,
        "F4": 0.5601,
        "Champion": 0.1906,
    },
    {
        "team": "Florida",
        "region": "South",
        "seed": 1,
        "R32": 0.9994,
        "S16": 0.8684,
        "E8": 0.6536,
        "F4": 0.3549,
        "Champion": 0.0726,
    },
    {
        "team": "Houston",
        "region": "South",
        "seed": 2,
        "R32": 0.9929,
        "S16": 0.8564,
        "E8": 0.4825,
        "F4": 0.2756,
        "Champion": 0.0529,
    },
    {
        "team": "Purdue",
        "region": "West",
        "seed": 2,
        "R32": 0.9945,
        "S16": 0.8774,
        "E8": 0.6397,
        "F4": 0.2731,
        "Champion": 0.0507,
    },
    {
        "team": "Illinois",
        "region": "South",
        "seed": 3,
        "R32": 0.9911,
        "S16": 0.8679,
        "E8": 0.4678,
        "F4": 0.2591,
        "Champion": 0.0496,
    },
    {
        "team": "Iowa St.",
        "region": "Midwest",
        "seed": 2,
        "R32": 0.995,
        "S16": 0.8508,
        "E8": 0.6023,
        "F4": 0.2298,
        "Champion": 0.0401,
    },
    {
        "team": "Connecticut",
        "region": "East",
        "seed": 2,
        "R32": 0.9876,
        "S16": 0.738,
        "E8": 0.4089,
        "F4": 0.1107,
        "Champion": 0.0111,
    },
    {
        "team": "Michigan St.",
        "region": "East",
        "seed": 3,
        "R32": 0.9693,
        "S16": 0.601,
        "E8": 0.3263,
        "F4": 0.0832,
        "Champion": 0.0063,
    },
    {
        "team": "Gonzaga",
        "region": "West",
        "seed": 3,
        "R32": 0.9836,
        "S16": 0.7179,
        "E8": 0.2667,
        "F4": 0.0766,
        "Champion": 0.0058,
    },
    {
        "team": "Vanderbilt",
        "region": "South",
        "seed": 5,
        "R32": 0.9233,
        "S16": 0.5661,
        "E8": 0.2005,
        "F4": 0.0695,
        "Champion": 0.0049,
    },
    {
        "team": "Virginia",
        "region": "Midwest",
        "seed": 3,
        "R32": 0.9764,
        "S16": 0.5723,
        "E8": 0.2162,
        "F4": 0.0559,
        "Champion": 0.0037,
    },
    {
        "team": "Texas Tech",
        "region": "Midwest",
        "seed": 5,
        "R32": 0.8933,
        "S16": 0.4706,
        "E8": 0.0951,
        "F4": 0.0383,
        "Champion": 0.0025,
    },
    {
        "team": "Alabama",
        "region": "Midwest",
        "seed": 4,
        "R32": 0.934,
        "S16": 0.5068,
        "E8": 0.1001,
        "F4": 0.0382,
        "Champion": 0.0025,
    },
    {
        "team": "Louisville",
        "region": "East",
        "seed": 6,
        "R32": 0.812,
        "S16": 0.3651,
        "E8": 0.1758,
        "F4": 0.0339,
        "Champion": 0.0024,
    },
    {
        "team": "Arkansas",
        "region": "West",
        "seed": 4,
        "R32": 0.9604,
        "S16": 0.5799,
        "E8": 0.1271,
        "F4": 0.0471,
        "Champion": 0.0024,
    },
    {
        "team": "St. John's",
        "region": "East",
        "seed": 5,
        "R32": 0.8988,
        "S16": 0.5442,
        "E8": 0.0967,
        "F4": 0.0431,
        "Champion": 0.002,
    },
    {
        "team": "Tennessee",
        "region": "Midwest",
        "seed": 6,
        "R32": 0.7773,
        "S16": 0.3747,
        "E8": 0.13,
        "F4": 0.0288,
        "Champion": 0.0014,
    },
    {
        "team": "Nebraska",
        "region": "South",
        "seed": 4,
        "R32": 0.9714,
        "S16": 0.4229,
        "E8": 0.1077,
        "F4": 0.0244,
        "Champion": 0.001,
    },
    {
        "team": "Wisconsin",
        "region": "West",
        "seed": 5,
        "R32": 0.9187,
        "S16": 0.4123,
        "E8": 0.0717,
        "F4": 0.0224,
        "Champion": 0.0006,
    },
    {
        "team": "Kansas",
        "region": "East",
        "seed": 4,
        "R32": 0.933,
        "S16": 0.4346,
        "E8": 0.0571,
        "F4": 0.0195,
        "Champion": 0.0004,
    },
    {
        "team": "Ohio St.",
        "region": "East",
        "seed": 8,
        "R32": 0.7293,
        "S16": 0.066,
        "E8": 0.028,
        "F4": 0.0085,
        "Champion": 0.0002,
    },
    {
        "team": "Iowa",
        "region": "South",
        "seed": 9,
        "R32": 0.6062,
        "S16": 0.0864,
        "E8": 0.0278,
        "F4": 0.0066,
        "Champion": 0.0002,
    },
    {
        "team": "North Carolina",
        "region": "South",
        "seed": 6,
        "R32": 0.6644,
        "S16": 0.1,
        "E8": 0.0177,
        "F4": 0.0029,
        "Champion": 0.0002,
    },
]

# ── Per-region bracket (most likely outcome path) ────────────────────────────
REGIONS_DATA = {
    "East": {
        "R64": [
            {
                "a": {
                    "seed": 1,
                    "team": "Duke",
                },
                "b": {
                    "seed": 16,
                    "team": "Siena",
                },
                "winner": "Duke",
                "upset": False,
            },
            {
                "a": {
                    "seed": 8,
                    "team": "Ohio St.",
                },
                "b": {
                    "seed": 9,
                    "team": "TCU",
                },
                "winner": "Ohio St.",
                "upset": False,
            },
            {
                "a": {
                    "seed": 5,
                    "team": "St. John's",
                },
                "b": {
                    "seed": 12,
                    "team": "Northern Iowa",
                },
                "winner": "St. John's",
                "upset": False,
            },
            {
                "a": {
                    "seed": 4,
                    "team": "Kansas",
                },
                "b": {
                    "seed": 13,
                    "team": "Cal Baptist",
                },
                "winner": "Kansas",
                "upset": False,
            },
            {
                "a": {
                    "seed": 6,
                    "team": "Louisville",
                },
                "b": {
                    "seed": 11,
                    "team": "South Florida",
                },
                "winner": "Louisville",
                "upset": False,
            },
            {
                "a": {
                    "seed": 3,
                    "team": "Michigan St.",
                },
                "b": {
                    "seed": 14,
                    "team": "North Dakota St.",
                },
                "winner": "Michigan St.",
                "upset": False,
            },
            {
                "a": {
                    "seed": 7,
                    "team": "UCLA",
                },
                "b": {
                    "seed": 10,
                    "team": "UCF",
                },
                "winner": "UCLA",
                "upset": False,
            },
            {
                "a": {
                    "seed": 2,
                    "team": "Connecticut",
                },
                "b": {
                    "seed": 15,
                    "team": "Furman",
                },
                "winner": "Connecticut",
                "upset": False,
            },
        ],
        "R32": [
            {
                "a": {
                    "seed": 1,
                    "team": "Duke",
                },
                "b": {
                    "seed": 8,
                    "team": "Ohio St.",
                },
                "winner": "Duke",
                "upset": False,
            },
            {
                "a": {
                    "seed": 5,
                    "team": "St. John's",
                },
                "b": {
                    "seed": 4,
                    "team": "Kansas",
                },
                "winner": "St. John's",
                "upset": True,
            },
            {
                "a": {
                    "seed": 6,
                    "team": "Louisville",
                },
                "b": {
                    "seed": 3,
                    "team": "Michigan St.",
                },
                "winner": "Michigan St.",
                "upset": False,
            },
            {
                "a": {
                    "seed": 7,
                    "team": "UCLA",
                },
                "b": {
                    "seed": 2,
                    "team": "Connecticut",
                },
                "winner": "Connecticut",
                "upset": False,
            },
        ],
        "S16": [
            {
                "a": {
                    "seed": 1,
                    "team": "Duke",
                },
                "b": {
                    "seed": 5,
                    "team": "St. John's",
                },
                "winner": "Duke",
                "upset": False,
            },
            {
                "a": {
                    "seed": 3,
                    "team": "Michigan St.",
                },
                "b": {
                    "seed": 2,
                    "team": "Connecticut",
                },
                "winner": "Connecticut",
                "upset": False,
            },
        ],
        "E8": [
            {
                "a": {
                    "seed": 1,
                    "team": "Duke",
                },
                "b": {
                    "seed": 2,
                    "team": "Connecticut",
                },
                "winner": "Duke",
                "upset": False,
            },
        ],
        "champion": "Duke",
    },
    "West": {
        "R64": [
            {
                "a": {
                    "seed": 1,
                    "team": "Arizona",
                },
                "b": {
                    "seed": 16,
                    "team": "LIU",
                },
                "winner": "Arizona",
                "upset": False,
            },
            {
                "a": {
                    "seed": 8,
                    "team": "Villanova",
                },
                "b": {
                    "seed": 9,
                    "team": "Utah St.",
                },
                "winner": "Utah St.",
                "upset": True,
            },
            {
                "a": {
                    "seed": 5,
                    "team": "Wisconsin",
                },
                "b": {
                    "seed": 12,
                    "team": "High Point",
                },
                "winner": "Wisconsin",
                "upset": False,
            },
            {
                "a": {
                    "seed": 4,
                    "team": "Arkansas",
                },
                "b": {
                    "seed": 13,
                    "team": "Hawaii",
                },
                "winner": "Arkansas",
                "upset": False,
            },
            {
                "a": {
                    "seed": 6,
                    "team": "BYU",
                },
                "b": {
                    "seed": 11,
                    "team": "N.C. State",
                },
                "winner": "BYU",
                "upset": False,
            },
            {
                "a": {
                    "seed": 3,
                    "team": "Gonzaga",
                },
                "b": {
                    "seed": 14,
                    "team": "Kennesaw St.",
                },
                "winner": "Gonzaga",
                "upset": False,
            },
            {
                "a": {
                    "seed": 7,
                    "team": "Miami FL",
                },
                "b": {
                    "seed": 10,
                    "team": "Missouri",
                },
                "winner": "Miami FL",
                "upset": False,
            },
            {
                "a": {
                    "seed": 2,
                    "team": "Purdue",
                },
                "b": {
                    "seed": 15,
                    "team": "Queens",
                },
                "winner": "Purdue",
                "upset": False,
            },
        ],
        "R32": [
            {
                "a": {
                    "seed": 1,
                    "team": "Arizona",
                },
                "b": {
                    "seed": 9,
                    "team": "Utah St.",
                },
                "winner": "Arizona",
                "upset": False,
            },
            {
                "a": {
                    "seed": 5,
                    "team": "Wisconsin",
                },
                "b": {
                    "seed": 4,
                    "team": "Arkansas",
                },
                "winner": "Arkansas",
                "upset": False,
            },
            {
                "a": {
                    "seed": 6,
                    "team": "BYU",
                },
                "b": {
                    "seed": 3,
                    "team": "Gonzaga",
                },
                "winner": "Gonzaga",
                "upset": False,
            },
            {
                "a": {
                    "seed": 7,
                    "team": "Miami FL",
                },
                "b": {
                    "seed": 2,
                    "team": "Purdue",
                },
                "winner": "Purdue",
                "upset": False,
            },
        ],
        "S16": [
            {
                "a": {
                    "seed": 1,
                    "team": "Arizona",
                },
                "b": {
                    "seed": 4,
                    "team": "Arkansas",
                },
                "winner": "Arizona",
                "upset": False,
            },
            {
                "a": {
                    "seed": 3,
                    "team": "Gonzaga",
                },
                "b": {
                    "seed": 2,
                    "team": "Purdue",
                },
                "winner": "Purdue",
                "upset": False,
            },
        ],
        "E8": [
            {
                "a": {
                    "seed": 1,
                    "team": "Arizona",
                },
                "b": {
                    "seed": 2,
                    "team": "Purdue",
                },
                "winner": "Arizona",
                "upset": False,
            },
        ],
        "champion": "Arizona",
    },
    "South": {
        "R64": [
            {
                "a": {
                    "seed": 1,
                    "team": "Florida",
                },
                "b": {
                    "seed": 16,
                    "team": "Lehigh",
                },
                "winner": "Florida",
                "upset": False,
            },
            {
                "a": {
                    "seed": 8,
                    "team": "Clemson",
                },
                "b": {
                    "seed": 9,
                    "team": "Iowa",
                },
                "winner": "Iowa",
                "upset": True,
            },
            {
                "a": {
                    "seed": 5,
                    "team": "Vanderbilt",
                },
                "b": {
                    "seed": 12,
                    "team": "McNeese St.",
                },
                "winner": "Vanderbilt",
                "upset": False,
            },
            {
                "a": {
                    "seed": 4,
                    "team": "Nebraska",
                },
                "b": {
                    "seed": 13,
                    "team": "Troy",
                },
                "winner": "Nebraska",
                "upset": False,
            },
            {
                "a": {
                    "seed": 6,
                    "team": "North Carolina",
                },
                "b": {
                    "seed": 11,
                    "team": "VCU",
                },
                "winner": "North Carolina",
                "upset": False,
            },
            {
                "a": {
                    "seed": 3,
                    "team": "Illinois",
                },
                "b": {
                    "seed": 14,
                    "team": "Penn",
                },
                "winner": "Illinois",
                "upset": False,
            },
            {
                "a": {
                    "seed": 7,
                    "team": "Saint Mary's",
                },
                "b": {
                    "seed": 10,
                    "team": "Texas A&M",
                },
                "winner": "Saint Mary's",
                "upset": False,
            },
            {
                "a": {
                    "seed": 2,
                    "team": "Houston",
                },
                "b": {
                    "seed": 15,
                    "team": "Idaho",
                },
                "winner": "Houston",
                "upset": False,
            },
        ],
        "R32": [
            {
                "a": {
                    "seed": 1,
                    "team": "Florida",
                },
                "b": {
                    "seed": 9,
                    "team": "Iowa",
                },
                "winner": "Florida",
                "upset": False,
            },
            {
                "a": {
                    "seed": 5,
                    "team": "Vanderbilt",
                },
                "b": {
                    "seed": 4,
                    "team": "Nebraska",
                },
                "winner": "Vanderbilt",
                "upset": True,
            },
            {
                "a": {
                    "seed": 6,
                    "team": "North Carolina",
                },
                "b": {
                    "seed": 3,
                    "team": "Illinois",
                },
                "winner": "Illinois",
                "upset": False,
            },
            {
                "a": {
                    "seed": 7,
                    "team": "Saint Mary's",
                },
                "b": {
                    "seed": 2,
                    "team": "Houston",
                },
                "winner": "Houston",
                "upset": False,
            },
        ],
        "S16": [
            {
                "a": {
                    "seed": 1,
                    "team": "Florida",
                },
                "b": {
                    "seed": 5,
                    "team": "Vanderbilt",
                },
                "winner": "Florida",
                "upset": False,
            },
            {
                "a": {
                    "seed": 3,
                    "team": "Illinois",
                },
                "b": {
                    "seed": 2,
                    "team": "Houston",
                },
                "winner": "Houston",
                "upset": False,
            },
        ],
        "E8": [
            {
                "a": {
                    "seed": 1,
                    "team": "Florida",
                },
                "b": {
                    "seed": 2,
                    "team": "Houston",
                },
                "winner": "Florida",
                "upset": False,
            },
        ],
        "champion": "Florida",
    },
    "Midwest": {
        "R64": [
            {
                "a": {
                    "seed": 1,
                    "team": "Michigan",
                },
                "b": {
                    "seed": 16,
                    "team": "UMBC",
                },
                "winner": "Michigan",
                "upset": False,
            },
            {
                "a": {
                    "seed": 8,
                    "team": "Georgia",
                },
                "b": {
                    "seed": 9,
                    "team": "Saint Louis",
                },
                "winner": "Georgia",
                "upset": False,
            },
            {
                "a": {
                    "seed": 5,
                    "team": "Texas Tech",
                },
                "b": {
                    "seed": 12,
                    "team": "Akron",
                },
                "winner": "Texas Tech",
                "upset": False,
            },
            {
                "a": {
                    "seed": 4,
                    "team": "Alabama",
                },
                "b": {
                    "seed": 13,
                    "team": "Hofstra",
                },
                "winner": "Alabama",
                "upset": False,
            },
            {
                "a": {
                    "seed": 6,
                    "team": "Tennessee",
                },
                "b": {
                    "seed": 11,
                    "team": "SMU",
                },
                "winner": "Tennessee",
                "upset": False,
            },
            {
                "a": {
                    "seed": 3,
                    "team": "Virginia",
                },
                "b": {
                    "seed": 14,
                    "team": "Wright St.",
                },
                "winner": "Virginia",
                "upset": False,
            },
            {
                "a": {
                    "seed": 7,
                    "team": "Kentucky",
                },
                "b": {
                    "seed": 10,
                    "team": "Santa Clara",
                },
                "winner": "Kentucky",
                "upset": False,
            },
            {
                "a": {
                    "seed": 2,
                    "team": "Iowa St.",
                },
                "b": {
                    "seed": 15,
                    "team": "Tennessee St.",
                },
                "winner": "Iowa St.",
                "upset": False,
            },
        ],
        "R32": [
            {
                "a": {
                    "seed": 1,
                    "team": "Michigan",
                },
                "b": {
                    "seed": 8,
                    "team": "Georgia",
                },
                "winner": "Michigan",
                "upset": False,
            },
            {
                "a": {
                    "seed": 5,
                    "team": "Texas Tech",
                },
                "b": {
                    "seed": 4,
                    "team": "Alabama",
                },
                "winner": "Texas Tech",
                "upset": True,
            },
            {
                "a": {
                    "seed": 6,
                    "team": "Tennessee",
                },
                "b": {
                    "seed": 3,
                    "team": "Virginia",
                },
                "winner": "Virginia",
                "upset": False,
            },
            {
                "a": {
                    "seed": 7,
                    "team": "Kentucky",
                },
                "b": {
                    "seed": 2,
                    "team": "Iowa St.",
                },
                "winner": "Iowa St.",
                "upset": False,
            },
        ],
        "S16": [
            {
                "a": {
                    "seed": 1,
                    "team": "Michigan",
                },
                "b": {
                    "seed": 5,
                    "team": "Texas Tech",
                },
                "winner": "Michigan",
                "upset": False,
            },
            {
                "a": {
                    "seed": 3,
                    "team": "Virginia",
                },
                "b": {
                    "seed": 2,
                    "team": "Iowa St.",
                },
                "winner": "Iowa St.",
                "upset": False,
            },
        ],
        "E8": [
            {
                "a": {
                    "seed": 1,
                    "team": "Michigan",
                },
                "b": {
                    "seed": 2,
                    "team": "Iowa St.",
                },
                "winner": "Michigan",
                "upset": False,
            },
        ],
        "champion": "Michigan",
    },
}

# ── Final Four & Championship ─────────────────────────────────────────────────
F4_DATA = [
    {
        "a": {
            "seed": 1,
            "team": "Duke",
        },
        "b": {
            "seed": 1,
            "team": "Florida",
        },
        "winner": "Duke",
    },
    {
        "a": {
            "seed": 1,
            "team": "Arizona",
        },
        "b": {
            "seed": 1,
            "team": "Michigan",
        },
        "winner": "Michigan",
    },
]

CHAMP_DATA = {
    "a": {
        "seed": 1,
        "team": "Duke",
    },
    "b": {
        "seed": 1,
        "team": "Michigan",
    },
    "winner": "Duke",
}

CHAMPION = "Duke"
