# ─── Bracket Data ───────────────────────────────────────────────────────────
# Auto-generated by generate_bracket_data.py on Selection Sunday.
# Do not edit manually — re-run the script to regenerate.

BRACKET_LOCKED = True

# ── Simulation metadata ───────────────────────────────────────────────────────
SIM_META = {
    "n_trials": 10000,
    "runtime_sec": 3.1,
    "model": "Formula-based log5",
    "season": "2025–26 NCAA Tournament",
}

# ── Round-by-round probabilities ─────────────────────────────────────────────
SIM_DATA = [
    {
        "team": "Duke",
        "region": "East",
        "seed": 1,
        "R32": 1.0,
        "S16": 0.9987,
        "E8": 0.9261,
        "F4": 0.8212,
        "Champion": 0.283,
    },
    {
        "team": "Michigan",
        "region": "Midwest",
        "seed": 1,
        "R32": 1.0,
        "S16": 0.9977,
        "E8": 0.9438,
        "F4": 0.8093,
        "Champion": 0.2338,
    },
    {
        "team": "Arizona",
        "region": "West",
        "seed": 1,
        "R32": 1.0,
        "S16": 0.9983,
        "E8": 0.9273,
        "F4": 0.7876,
        "Champion": 0.1873,
    },
    {
        "team": "Florida",
        "region": "South",
        "seed": 1,
        "R32": 1.0,
        "S16": 0.999,
        "E8": 0.8722,
        "F4": 0.6506,
        "Champion": 0.0742,
    },
    {
        "team": "Houston",
        "region": "South",
        "seed": 2,
        "R32": 1.0,
        "S16": 0.9929,
        "E8": 0.8591,
        "F4": 0.4756,
        "Champion": 0.0532,
    },
    {
        "team": "Illinois",
        "region": "South",
        "seed": 3,
        "R32": 1.0,
        "S16": 0.9935,
        "E8": 0.8753,
        "F4": 0.4767,
        "Champion": 0.0468,
    },
    {
        "team": "Purdue",
        "region": "West",
        "seed": 2,
        "R32": 1.0,
        "S16": 0.9931,
        "E8": 0.8647,
        "F4": 0.6055,
        "Champion": 0.0378,
    },
    {
        "team": "Iowa St.",
        "region": "Midwest",
        "seed": 2,
        "R32": 1.0,
        "S16": 0.9939,
        "E8": 0.8396,
        "F4": 0.5992,
        "Champion": 0.0365,
    },
    {
        "team": "Connecticut",
        "region": "East",
        "seed": 2,
        "R32": 1.0,
        "S16": 0.9893,
        "E8": 0.7417,
        "F4": 0.4165,
        "Champion": 0.0084,
    },
    {
        "team": "Vanderbilt",
        "region": "South",
        "seed": 5,
        "R32": 1.0,
        "S16": 0.9311,
        "E8": 0.581,
        "F4": 0.2034,
        "Champion": 0.0072,
    },
    {
        "team": "Michigan St.",
        "region": "East",
        "seed": 3,
        "R32": 1.0,
        "S16": 0.9664,
        "E8": 0.6166,
        "F4": 0.3272,
        "Champion": 0.0067,
    },
    {
        "team": "Gonzaga",
        "region": "West",
        "seed": 3,
        "R32": 1.0,
        "S16": 0.9812,
        "E8": 0.7138,
        "F4": 0.2885,
        "Champion": 0.0058,
    },
    {
        "team": "St. John's",
        "region": "East",
        "seed": 5,
        "R32": 1.0,
        "S16": 0.9014,
        "E8": 0.5249,
        "F4": 0.0824,
        "Champion": 0.0033,
    },
    {
        "team": "Alabama",
        "region": "Midwest",
        "seed": 4,
        "R32": 1.0,
        "S16": 0.9388,
        "E8": 0.5041,
        "F4": 0.0901,
        "Champion": 0.0027,
    },
    {
        "team": "Virginia",
        "region": "Midwest",
        "seed": 3,
        "R32": 1.0,
        "S16": 0.9737,
        "E8": 0.5567,
        "F4": 0.209,
        "Champion": 0.0026,
    },
    {
        "team": "Texas Tech",
        "region": "Midwest",
        "seed": 5,
        "R32": 1.0,
        "S16": 0.8972,
        "E8": 0.4761,
        "F4": 0.0847,
        "Champion": 0.0022,
    },
    {
        "team": "Arkansas",
        "region": "West",
        "seed": 4,
        "R32": 1.0,
        "S16": 0.9551,
        "E8": 0.5469,
        "F4": 0.1074,
        "Champion": 0.002,
    },
    {
        "team": "Kansas",
        "region": "East",
        "seed": 4,
        "R32": 1.0,
        "S16": 0.9376,
        "E8": 0.4495,
        "F4": 0.0654,
        "Champion": 0.0012,
    },
    {
        "team": "Tennessee",
        "region": "Midwest",
        "seed": 6,
        "R32": 1.0,
        "S16": 0.7702,
        "E8": 0.3879,
        "F4": 0.132,
        "Champion": 0.0012,
    },
    {
        "team": "Wisconsin",
        "region": "West",
        "seed": 5,
        "R32": 1.0,
        "S16": 0.925,
        "E8": 0.4433,
        "F4": 0.0808,
        "Champion": 0.0011,
    },
    {
        "team": "Louisville",
        "region": "East",
        "seed": 6,
        "R32": 1.0,
        "S16": 0.8294,
        "E8": 0.3562,
        "F4": 0.1679,
        "Champion": 0.0009,
    },
    {
        "team": "Nebraska",
        "region": "South",
        "seed": 4,
        "R32": 1.0,
        "S16": 0.9732,
        "E8": 0.4088,
        "F4": 0.1058,
        "Champion": 0.0009,
    },
    {
        "team": "UCLA",
        "region": "East",
        "seed": 7,
        "R32": 1.0,
        "S16": 0.761,
        "E8": 0.2272,
        "F4": 0.081,
        "Champion": 0.0004,
    },
    {
        "team": "Ohio St.",
        "region": "East",
        "seed": 8,
        "R32": 1.0,
        "S16": 0.7286,
        "E8": 0.0637,
        "F4": 0.0281,
        "Champion": 0.0001,
    },
    {
        "team": "N.C. State",
        "region": "West",
        "seed": 11,
        "R32": 1.0,
        "S16": 0.4126,
        "E8": 0.1018,
        "F4": 0.0209,
        "Champion": 0.0001,
    },
]

# ── Per-region bracket (most likely outcome path) ────────────────────────────
REGIONS_DATA = {
    "East": {
        "R64": [
            {
                "a": {
                    "seed": 1,
                    "team": "Duke",
                },
                "b": {
                    "seed": 16,
                    "team": "Siena",
                },
                "winner": "Duke",
                "upset": False,
            },
            {
                "a": {
                    "seed": 8,
                    "team": "Ohio St.",
                },
                "b": {
                    "seed": 9,
                    "team": "TCU",
                },
                "winner": "Ohio St.",
                "upset": False,
            },
            {
                "a": {
                    "seed": 5,
                    "team": "St. John's",
                },
                "b": {
                    "seed": 12,
                    "team": "Northern Iowa",
                },
                "winner": "St. John's",
                "upset": False,
            },
            {
                "a": {
                    "seed": 4,
                    "team": "Kansas",
                },
                "b": {
                    "seed": 13,
                    "team": "Cal Baptist",
                },
                "winner": "Kansas",
                "upset": False,
            },
            {
                "a": {
                    "seed": 6,
                    "team": "Louisville",
                },
                "b": {
                    "seed": 11,
                    "team": "South Florida",
                },
                "winner": "Louisville",
                "upset": False,
            },
            {
                "a": {
                    "seed": 3,
                    "team": "Michigan St.",
                },
                "b": {
                    "seed": 14,
                    "team": "North Dakota St.",
                },
                "winner": "Michigan St.",
                "upset": False,
            },
            {
                "a": {
                    "seed": 7,
                    "team": "UCLA",
                },
                "b": {
                    "seed": 10,
                    "team": "UCF",
                },
                "winner": "UCLA",
                "upset": False,
            },
            {
                "a": {
                    "seed": 2,
                    "team": "Connecticut",
                },
                "b": {
                    "seed": 15,
                    "team": "Furman",
                },
                "winner": "Connecticut",
                "upset": False,
            },
        ],
        "R32": [
            {
                "a": {
                    "seed": 1,
                    "team": "Duke",
                },
                "b": {
                    "seed": 8,
                    "team": "Ohio St.",
                },
                "winner": "Duke",
                "upset": False,
            },
            {
                "a": {
                    "seed": 5,
                    "team": "St. John's",
                },
                "b": {
                    "seed": 4,
                    "team": "Kansas",
                },
                "winner": "St. John's",
                "upset": True,
            },
            {
                "a": {
                    "seed": 6,
                    "team": "Louisville",
                },
                "b": {
                    "seed": 3,
                    "team": "Michigan St.",
                },
                "winner": "Michigan St.",
                "upset": False,
            },
            {
                "a": {
                    "seed": 7,
                    "team": "UCLA",
                },
                "b": {
                    "seed": 2,
                    "team": "Connecticut",
                },
                "winner": "Connecticut",
                "upset": False,
            },
        ],
        "S16": [
            {
                "a": {
                    "seed": 1,
                    "team": "Duke",
                },
                "b": {
                    "seed": 5,
                    "team": "St. John's",
                },
                "winner": "Duke",
                "upset": False,
            },
            {
                "a": {
                    "seed": 3,
                    "team": "Michigan St.",
                },
                "b": {
                    "seed": 2,
                    "team": "Connecticut",
                },
                "winner": "Connecticut",
                "upset": False,
            },
        ],
        "E8": [
            {
                "a": {
                    "seed": 1,
                    "team": "Duke",
                },
                "b": {
                    "seed": 2,
                    "team": "Connecticut",
                },
                "winner": "Duke",
                "upset": False,
            },
        ],
        "champion": "Duke",
    },
    "West": {
        "R64": [
            {
                "a": {
                    "seed": 1,
                    "team": "Arizona",
                },
                "b": {
                    "seed": 16,
                    "team": "LIU",
                },
                "winner": "Arizona",
                "upset": False,
            },
            {
                "a": {
                    "seed": 8,
                    "team": "Villanova",
                },
                "b": {
                    "seed": 9,
                    "team": "Utah St.",
                },
                "winner": "Utah St.",
                "upset": True,
            },
            {
                "a": {
                    "seed": 5,
                    "team": "Wisconsin",
                },
                "b": {
                    "seed": 12,
                    "team": "High Point",
                },
                "winner": "Wisconsin",
                "upset": False,
            },
            {
                "a": {
                    "seed": 4,
                    "team": "Arkansas",
                },
                "b": {
                    "seed": 13,
                    "team": "Hawaii",
                },
                "winner": "Arkansas",
                "upset": False,
            },
            {
                "a": {
                    "seed": 6,
                    "team": "BYU",
                },
                "b": {
                    "seed": 11,
                    "team": "N.C. State",
                },
                "winner": "BYU",
                "upset": False,
            },
            {
                "a": {
                    "seed": 3,
                    "team": "Gonzaga",
                },
                "b": {
                    "seed": 14,
                    "team": "Kennesaw St.",
                },
                "winner": "Gonzaga",
                "upset": False,
            },
            {
                "a": {
                    "seed": 7,
                    "team": "Miami FL",
                },
                "b": {
                    "seed": 10,
                    "team": "Missouri",
                },
                "winner": "Miami FL",
                "upset": False,
            },
            {
                "a": {
                    "seed": 2,
                    "team": "Purdue",
                },
                "b": {
                    "seed": 15,
                    "team": "Queens",
                },
                "winner": "Purdue",
                "upset": False,
            },
        ],
        "R32": [
            {
                "a": {
                    "seed": 1,
                    "team": "Arizona",
                },
                "b": {
                    "seed": 9,
                    "team": "Utah St.",
                },
                "winner": "Arizona",
                "upset": False,
            },
            {
                "a": {
                    "seed": 5,
                    "team": "Wisconsin",
                },
                "b": {
                    "seed": 4,
                    "team": "Arkansas",
                },
                "winner": "Arkansas",
                "upset": False,
            },
            {
                "a": {
                    "seed": 6,
                    "team": "BYU",
                },
                "b": {
                    "seed": 3,
                    "team": "Gonzaga",
                },
                "winner": "Gonzaga",
                "upset": False,
            },
            {
                "a": {
                    "seed": 7,
                    "team": "Miami FL",
                },
                "b": {
                    "seed": 2,
                    "team": "Purdue",
                },
                "winner": "Purdue",
                "upset": False,
            },
        ],
        "S16": [
            {
                "a": {
                    "seed": 1,
                    "team": "Arizona",
                },
                "b": {
                    "seed": 4,
                    "team": "Arkansas",
                },
                "winner": "Arizona",
                "upset": False,
            },
            {
                "a": {
                    "seed": 3,
                    "team": "Gonzaga",
                },
                "b": {
                    "seed": 2,
                    "team": "Purdue",
                },
                "winner": "Purdue",
                "upset": False,
            },
        ],
        "E8": [
            {
                "a": {
                    "seed": 1,
                    "team": "Arizona",
                },
                "b": {
                    "seed": 2,
                    "team": "Purdue",
                },
                "winner": "Arizona",
                "upset": False,
            },
        ],
        "champion": "Arizona",
    },
    "South": {
        "R64": [
            {
                "a": {
                    "seed": 1,
                    "team": "Florida",
                },
                "b": {
                    "seed": 16,
                    "team": "Lehigh",
                },
                "winner": "Florida",
                "upset": False,
            },
            {
                "a": {
                    "seed": 8,
                    "team": "Clemson",
                },
                "b": {
                    "seed": 9,
                    "team": "Iowa",
                },
                "winner": "Iowa",
                "upset": True,
            },
            {
                "a": {
                    "seed": 5,
                    "team": "Vanderbilt",
                },
                "b": {
                    "seed": 12,
                    "team": "McNeese St.",
                },
                "winner": "Vanderbilt",
                "upset": False,
            },
            {
                "a": {
                    "seed": 4,
                    "team": "Nebraska",
                },
                "b": {
                    "seed": 13,
                    "team": "Troy",
                },
                "winner": "Nebraska",
                "upset": False,
            },
            {
                "a": {
                    "seed": 6,
                    "team": "North Carolina",
                },
                "b": {
                    "seed": 11,
                    "team": "VCU",
                },
                "winner": "North Carolina",
                "upset": False,
            },
            {
                "a": {
                    "seed": 3,
                    "team": "Illinois",
                },
                "b": {
                    "seed": 14,
                    "team": "Penn",
                },
                "winner": "Illinois",
                "upset": False,
            },
            {
                "a": {
                    "seed": 7,
                    "team": "Saint Mary's",
                },
                "b": {
                    "seed": 10,
                    "team": "Texas A&M",
                },
                "winner": "Saint Mary's",
                "upset": False,
            },
            {
                "a": {
                    "seed": 2,
                    "team": "Houston",
                },
                "b": {
                    "seed": 15,
                    "team": "Idaho",
                },
                "winner": "Houston",
                "upset": False,
            },
        ],
        "R32": [
            {
                "a": {
                    "seed": 1,
                    "team": "Florida",
                },
                "b": {
                    "seed": 9,
                    "team": "Iowa",
                },
                "winner": "Florida",
                "upset": False,
            },
            {
                "a": {
                    "seed": 5,
                    "team": "Vanderbilt",
                },
                "b": {
                    "seed": 4,
                    "team": "Nebraska",
                },
                "winner": "Vanderbilt",
                "upset": True,
            },
            {
                "a": {
                    "seed": 6,
                    "team": "North Carolina",
                },
                "b": {
                    "seed": 3,
                    "team": "Illinois",
                },
                "winner": "Illinois",
                "upset": False,
            },
            {
                "a": {
                    "seed": 7,
                    "team": "Saint Mary's",
                },
                "b": {
                    "seed": 2,
                    "team": "Houston",
                },
                "winner": "Houston",
                "upset": False,
            },
        ],
        "S16": [
            {
                "a": {
                    "seed": 1,
                    "team": "Florida",
                },
                "b": {
                    "seed": 5,
                    "team": "Vanderbilt",
                },
                "winner": "Florida",
                "upset": False,
            },
            {
                "a": {
                    "seed": 3,
                    "team": "Illinois",
                },
                "b": {
                    "seed": 2,
                    "team": "Houston",
                },
                "winner": "Houston",
                "upset": False,
            },
        ],
        "E8": [
            {
                "a": {
                    "seed": 1,
                    "team": "Florida",
                },
                "b": {
                    "seed": 2,
                    "team": "Houston",
                },
                "winner": "Florida",
                "upset": False,
            },
        ],
        "champion": "Florida",
    },
    "Midwest": {
        "R64": [
            {
                "a": {
                    "seed": 1,
                    "team": "Michigan",
                },
                "b": {
                    "seed": 16,
                    "team": "UMBC",
                },
                "winner": "Michigan",
                "upset": False,
            },
            {
                "a": {
                    "seed": 8,
                    "team": "Georgia",
                },
                "b": {
                    "seed": 9,
                    "team": "Saint Louis",
                },
                "winner": "Georgia",
                "upset": False,
            },
            {
                "a": {
                    "seed": 5,
                    "team": "Texas Tech",
                },
                "b": {
                    "seed": 12,
                    "team": "Akron",
                },
                "winner": "Texas Tech",
                "upset": False,
            },
            {
                "a": {
                    "seed": 4,
                    "team": "Alabama",
                },
                "b": {
                    "seed": 13,
                    "team": "Hofstra",
                },
                "winner": "Alabama",
                "upset": False,
            },
            {
                "a": {
                    "seed": 6,
                    "team": "Tennessee",
                },
                "b": {
                    "seed": 11,
                    "team": "SMU",
                },
                "winner": "Tennessee",
                "upset": False,
            },
            {
                "a": {
                    "seed": 3,
                    "team": "Virginia",
                },
                "b": {
                    "seed": 14,
                    "team": "Wright St.",
                },
                "winner": "Virginia",
                "upset": False,
            },
            {
                "a": {
                    "seed": 7,
                    "team": "Kentucky",
                },
                "b": {
                    "seed": 10,
                    "team": "Santa Clara",
                },
                "winner": "Kentucky",
                "upset": False,
            },
            {
                "a": {
                    "seed": 2,
                    "team": "Iowa St.",
                },
                "b": {
                    "seed": 15,
                    "team": "Tennessee St.",
                },
                "winner": "Iowa St.",
                "upset": False,
            },
        ],
        "R32": [
            {
                "a": {
                    "seed": 1,
                    "team": "Michigan",
                },
                "b": {
                    "seed": 8,
                    "team": "Georgia",
                },
                "winner": "Michigan",
                "upset": False,
            },
            {
                "a": {
                    "seed": 5,
                    "team": "Texas Tech",
                },
                "b": {
                    "seed": 4,
                    "team": "Alabama",
                },
                "winner": "Texas Tech",
                "upset": True,
            },
            {
                "a": {
                    "seed": 6,
                    "team": "Tennessee",
                },
                "b": {
                    "seed": 3,
                    "team": "Virginia",
                },
                "winner": "Virginia",
                "upset": False,
            },
            {
                "a": {
                    "seed": 7,
                    "team": "Kentucky",
                },
                "b": {
                    "seed": 2,
                    "team": "Iowa St.",
                },
                "winner": "Iowa St.",
                "upset": False,
            },
        ],
        "S16": [
            {
                "a": {
                    "seed": 1,
                    "team": "Michigan",
                },
                "b": {
                    "seed": 5,
                    "team": "Texas Tech",
                },
                "winner": "Michigan",
                "upset": False,
            },
            {
                "a": {
                    "seed": 3,
                    "team": "Virginia",
                },
                "b": {
                    "seed": 2,
                    "team": "Iowa St.",
                },
                "winner": "Iowa St.",
                "upset": False,
            },
        ],
        "E8": [
            {
                "a": {
                    "seed": 1,
                    "team": "Michigan",
                },
                "b": {
                    "seed": 2,
                    "team": "Iowa St.",
                },
                "winner": "Michigan",
                "upset": False,
            },
        ],
        "champion": "Michigan",
    },
}

# ── Final Four & Championship ─────────────────────────────────────────────────
F4_DATA = [
    {
        "a": {
            "seed": 1,
            "team": "Duke",
        },
        "b": {
            "seed": 1,
            "team": "Florida",
        },
        "winner": "Duke",
    },
    {
        "a": {
            "seed": 1,
            "team": "Arizona",
        },
        "b": {
            "seed": 1,
            "team": "Michigan",
        },
        "winner": "Michigan",
    },
]

CHAMP_DATA = {
    "a": {
        "seed": 1,
        "team": "Duke",
    },
    "b": {
        "seed": 1,
        "team": "Michigan",
    },
    "winner": "Duke",
}

CHAMPION = "Duke"
