name: 'cbb_analytics'
version: '1.0.0'
config-version: 2

profile: 'cbb_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  cbb_analytics:
    staging:
      +materialized: view        # staging models are views
      +schema: staging
    marts:
      +materialized: table       # mart models are tables
      +schema: marts