# ─── Bracket Data ───────────────────────────────────────────────────────────
# Auto-generated by generate_bracket_data.py on Selection Sunday.
# Do not edit manually — re-run the script to regenerate.

BRACKET_LOCKED = True

# ── Simulation metadata ───────────────────────────────────────────────────────
SIM_META = {
    "n_trials": 10000,
    "runtime_sec": 3.2,
    "model": "Formula-based log5",
    "season": "2025–26 NCAA Tournament",
}

# ── Round-by-round probabilities ─────────────────────────────────────────────
SIM_DATA = [
    {
        "team": "Duke",
        "region": "East",
        "seed": 1,
        "R32": 0.9985,
        "S16": 0.9225,
        "E8": 0.82,
        "F4": 0.6918,
        "Champion": 0.2908,
    },
    {
        "team": "Michigan",
        "region": "Midwest",
        "seed": 1,
        "R32": 0.9973,
        "S16": 0.9424,
        "E8": 0.794,
        "F4": 0.6052,
        "Champion": 0.211,
    },
    {
        "team": "Arizona",
        "region": "West",
        "seed": 1,
        "R32": 0.9981,
        "S16": 0.9254,
        "E8": 0.7846,
        "F4": 0.5792,
        "Champion": 0.1924,
    },
    {
        "team": "Florida",
        "region": "South",
        "seed": 1,
        "R32": 0.9992,
        "S16": 0.8762,
        "E8": 0.6651,
        "F4": 0.3545,
        "Champion": 0.0714,
    },
    {
        "team": "Houston",
        "region": "South",
        "seed": 2,
        "R32": 0.9923,
        "S16": 0.8509,
        "E8": 0.4716,
        "F4": 0.2658,
        "Champion": 0.0545,
    },
    {
        "team": "Illinois",
        "region": "South",
        "seed": 3,
        "R32": 0.9924,
        "S16": 0.8774,
        "E8": 0.4788,
        "F4": 0.2695,
        "Champion": 0.049,
    },
    {
        "team": "Purdue",
        "region": "West",
        "seed": 2,
        "R32": 0.9944,
        "S16": 0.8723,
        "E8": 0.6314,
        "F4": 0.2633,
        "Champion": 0.0481,
    },
    {
        "team": "Iowa St.",
        "region": "Midwest",
        "seed": 2,
        "R32": 0.9946,
        "S16": 0.8439,
        "E8": 0.596,
        "F4": 0.2295,
        "Champion": 0.0369,
    },
    {
        "team": "Connecticut",
        "region": "East",
        "seed": 2,
        "R32": 0.9914,
        "S16": 0.7513,
        "E8": 0.4214,
        "F4": 0.1081,
        "Champion": 0.0097,
    },
    {
        "team": "Vanderbilt",
        "region": "South",
        "seed": 5,
        "R32": 0.9223,
        "S16": 0.5752,
        "E8": 0.1916,
        "F4": 0.068,
        "Champion": 0.006,
    },
    {
        "team": "Gonzaga",
        "region": "West",
        "seed": 3,
        "R32": 0.9826,
        "S16": 0.7113,
        "E8": 0.2687,
        "F4": 0.0704,
        "Champion": 0.0059,
    },
    {
        "team": "Michigan St.",
        "region": "East",
        "seed": 3,
        "R32": 0.966,
        "S16": 0.605,
        "E8": 0.3237,
        "F4": 0.0808,
        "Champion": 0.0055,
    },
    {
        "team": "Virginia",
        "region": "Midwest",
        "seed": 3,
        "R32": 0.9764,
        "S16": 0.5772,
        "E8": 0.211,
        "F4": 0.0519,
        "Champion": 0.003,
    },
    {
        "team": "Arkansas",
        "region": "West",
        "seed": 4,
        "R32": 0.9586,
        "S16": 0.5706,
        "E8": 0.1198,
        "F4": 0.0473,
        "Champion": 0.0026,
    },
    {
        "team": "Alabama",
        "region": "Midwest",
        "seed": 4,
        "R32": 0.9333,
        "S16": 0.4975,
        "E8": 0.0957,
        "F4": 0.0379,
        "Champion": 0.0025,
    },
    {
        "team": "Texas Tech",
        "region": "Midwest",
        "seed": 5,
        "R32": 0.8971,
        "S16": 0.4822,
        "E8": 0.0946,
        "F4": 0.0377,
        "Champion": 0.0023,
    },
    {
        "team": "Louisville",
        "region": "East",
        "seed": 6,
        "R32": 0.8217,
        "S16": 0.3633,
        "E8": 0.1692,
        "F4": 0.0351,
        "Champion": 0.0019,
    },
    {
        "team": "St. John's",
        "region": "East",
        "seed": 5,
        "R32": 0.8983,
        "S16": 0.5327,
        "E8": 0.0885,
        "F4": 0.0401,
        "Champion": 0.0018,
    },
    {
        "team": "Wisconsin",
        "region": "West",
        "seed": 5,
        "R32": 0.9233,
        "S16": 0.4201,
        "E8": 0.0722,
        "F4": 0.0219,
        "Champion": 0.0011,
    },
    {
        "team": "Tennessee",
        "region": "Midwest",
        "seed": 6,
        "R32": 0.7681,
        "S16": 0.3677,
        "E8": 0.1378,
        "F4": 0.0298,
        "Champion": 0.0011,
    },
    {
        "team": "Kansas",
        "region": "East",
        "seed": 4,
        "R32": 0.9365,
        "S16": 0.4463,
        "E8": 0.0585,
        "F4": 0.022,
        "Champion": 0.0007,
    },
    {
        "team": "Nebraska",
        "region": "South",
        "seed": 4,
        "R32": 0.9739,
        "S16": 0.4139,
        "E8": 0.103,
        "F4": 0.0255,
        "Champion": 0.0006,
    },
    {
        "team": "BYU",
        "region": "West",
        "seed": 6,
        "R32": 0.5953,
        "S16": 0.1876,
        "E8": 0.0422,
        "F4": 0.0063,
        "Champion": 0.0002,
    },
    {
        "team": "North Carolina",
        "region": "South",
        "seed": 6,
        "R32": 0.6595,
        "S16": 0.0966,
        "E8": 0.0178,
        "F4": 0.003,
        "Champion": 0.0002,
    },
    {
        "team": "UCLA",
        "region": "East",
        "seed": 7,
        "R32": 0.7627,
        "S16": 0.2209,
        "E8": 0.0764,
        "F4": 0.0108,
        "Champion": 0.0001,
    },
    {
        "team": "Ohio St.",
        "region": "East",
        "seed": 8,
        "R32": 0.7297,
        "S16": 0.0684,
        "E8": 0.0306,
        "F4": 0.0101,
        "Champion": 0.0001,
    },
    {
        "team": "Utah St.",
        "region": "West",
        "seed": 9,
        "R32": 0.5428,
        "S16": 0.0428,
        "E8": 0.0135,
        "F4": 0.0033,
        "Champion": 0.0001,
    },
    {
        "team": "N.C. State",
        "region": "West",
        "seed": 11,
        "R32": 0.4047,
        "S16": 0.1001,
        "E8": 0.0165,
        "F4": 0.0018,
        "Champion": 0.0001,
    },
    {
        "team": "Villanova",
        "region": "West",
        "seed": 8,
        "R32": 0.4572,
        "S16": 0.0317,
        "E8": 0.0097,
        "F4": 0.0024,
        "Champion": 0.0001,
    },
    {
        "team": "Miami FL",
        "region": "West",
        "seed": 7,
        "R32": 0.6442,
        "S16": 0.0948,
        "E8": 0.033,
        "F4": 0.0034,
        "Champion": 0.0001,
    },
    {
        "team": "Iowa",
        "region": "South",
        "seed": 9,
        "R32": 0.6081,
        "S16": 0.0881,
        "E8": 0.0319,
        "F4": 0.0065,
        "Champion": 0.0001,
    },
    {
        "team": "Saint Mary's",
        "region": "South",
        "seed": 7,
        "R32": 0.6489,
        "S16": 0.1116,
        "E8": 0.0237,
        "F4": 0.0056,
        "Champion": 0.0001,
    },
    {
        "team": "Siena",
        "region": "East",
        "seed": 16,
        "R32": 0.0015,
        "S16": 0.0,
        "E8": 0.0,
        "F4": 0.0,
        "Champion": 0.0,
    },
    {
        "team": "TCU",
        "region": "East",
        "seed": 9,
        "R32": 0.2703,
        "S16": 0.0091,
        "E8": 0.0022,
        "F4": 0.0003,
        "Champion": 0.0,
    },
    {
        "team": "Northern Iowa",
        "region": "East",
        "seed": 12,
        "R32": 0.1017,
        "S16": 0.016,
        "E8": 0.0002,
        "F4": 0.0,
        "Champion": 0.0,
    },
    {
        "team": "Cal Baptist",
        "region": "East",
        "seed": 13,
        "R32": 0.0635,
        "S16": 0.005,
        "E8": 0.0,
        "F4": 0.0,
        "Champion": 0.0,
    },
    {
        "team": "South Florida",
        "region": "East",
        "seed": 11,
        "R32": 0.1783,
        "S16": 0.0294,
        "E8": 0.0047,
        "F4": 0.0005,
        "Champion": 0.0,
    },
    {
        "team": "North Dakota St.",
        "region": "East",
        "seed": 14,
        "R32": 0.034,
        "S16": 0.0023,
        "E8": 0.0,
        "F4": 0.0,
        "Champion": 0.0,
    },
    {
        "team": "Furman",
        "region": "East",
        "seed": 15,
        "R32": 0.0086,
        "S16": 0.0002,
        "E8": 0.0,
        "F4": 0.0,
        "Champion": 0.0,
    },
    {
        "team": "UCF",
        "region": "East",
        "seed": 10,
        "R32": 0.2373,
        "S16": 0.0276,
        "E8": 0.0046,
        "F4": 0.0004,
        "Champion": 0.0,
    },
    {
        "team": "LIU",
        "region": "West",
        "seed": 16,
        "R32": 0.0019,
        "S16": 0.0001,
        "E8": 0.0,
        "F4": 0.0,
        "Champion": 0.0,
    },
    {
        "team": "High Point",
        "region": "West",
        "seed": 12,
        "R32": 0.0767,
        "S16": 0.0057,
        "E8": 0.0001,
        "F4": 0.0,
        "Champion": 0.0,
    },
    {
        "team": "Hawaii",
        "region": "West",
        "seed": 13,
        "R32": 0.0414,
        "S16": 0.0036,
        "E8": 0.0001,
        "F4": 0.0,
        "Champion": 0.0,
    },
    {
        "team": "Kennesaw St.",
        "region": "West",
        "seed": 14,
        "R32": 0.0174,
        "S16": 0.001,
        "E8": 0.0,
        "F4": 0.0,
        "Champion": 0.0,
    },
    {
        "team": "Missouri",
        "region": "West",
        "seed": 10,
        "R32": 0.3558,
        "S16": 0.0327,
        "E8": 0.0082,
        "F4": 0.0007,
        "Champion": 0.0,
    },
    {
        "team": "Queens",
        "region": "West",
        "seed": 15,
        "R32": 0.0056,
        "S16": 0.0002,
        "E8": 0.0,
        "F4": 0.0,
        "Champion": 0.0,
    },
    {
        "team": "Lehigh",
        "region": "South",
        "seed": 16,
        "R32": 0.0008,
        "S16": 0.0,
        "E8": 0.0,
        "F4": 0.0,
        "Champion": 0.0,
    },
    {
        "team": "Troy",
        "region": "South",
        "seed": 13,
        "R32": 0.0261,
        "S16": 0.0005,
        "E8": 0.0,
        "F4": 0.0,
        "Champion": 0.0,
    },
    {
        "team": "VCU",
        "region": "South",
        "seed": 11,
        "R32": 0.3405,
        "S16": 0.0257,
        "E8": 0.0027,
        "F4": 0.0002,
        "Champion": 0.0,
    },
    {
        "team": "Penn",
        "region": "South",
        "seed": 14,
        "R32": 0.0076,
        "S16": 0.0003,
        "E8": 0.0,
        "F4": 0.0,
        "Champion": 0.0,
    },
    {
        "team": "Texas A&M",
        "region": "South",
        "seed": 10,
        "R32": 0.3511,
        "S16": 0.037,
        "E8": 0.0054,
        "F4": 0.0005,
        "Champion": 0.0,
    },
    {
        "team": "Idaho",
        "region": "South",
        "seed": 15,
        "R32": 0.0077,
        "S16": 0.0005,
        "E8": 0.0,
        "F4": 0.0,
        "Champion": 0.0,
    },
    {
        "team": "Clemson",
        "region": "South",
        "seed": 8,
        "R32": 0.3919,
        "S16": 0.0357,
        "E8": 0.0084,
        "F4": 0.0009,
        "Champion": 0.0,
    },
    {
        "team": "McNeese St.",
        "region": "South",
        "seed": 12,
        "R32": 0.0777,
        "S16": 0.0104,
        "E8": 0.0,
        "F4": 0.0,
        "Champion": 0.0,
    },
    {
        "team": "UMBC",
        "region": "Midwest",
        "seed": 16,
        "R32": 0.0027,
        "S16": 0.0003,
        "E8": 0.0,
        "F4": 0.0,
        "Champion": 0.0,
    },
    {
        "team": "Saint Louis",
        "region": "Midwest",
        "seed": 9,
        "R32": 0.42,
        "S16": 0.0188,
        "E8": 0.0038,
        "F4": 0.0002,
        "Champion": 0.0,
    },
    {
        "team": "Akron",
        "region": "Midwest",
        "seed": 12,
        "R32": 0.1029,
        "S16": 0.0137,
        "E8": 0.0009,
        "F4": 0.0001,
        "Champion": 0.0,
    },
    {
        "team": "Hofstra",
        "region": "Midwest",
        "seed": 13,
        "R32": 0.0667,
        "S16": 0.0066,
        "E8": 0.0001,
        "F4": 0.0,
        "Champion": 0.0,
    },
    {
        "team": "SMU",
        "region": "Midwest",
        "seed": 11,
        "R32": 0.2319,
        "S16": 0.0543,
        "E8": 0.0088,
        "F4": 0.0009,
        "Champion": 0.0,
    },
    {
        "team": "Wright St.",
        "region": "Midwest",
        "seed": 14,
        "R32": 0.0236,
        "S16": 0.0008,
        "E8": 0.0,
        "F4": 0.0,
        "Champion": 0.0,
    },
    {
        "team": "Kentucky",
        "region": "Midwest",
        "seed": 7,
        "R32": 0.5172,
        "S16": 0.0846,
        "E8": 0.026,
        "F4": 0.003,
        "Champion": 0.0,
    },
    {
        "team": "Tennessee St.",
        "region": "Midwest",
        "seed": 15,
        "R32": 0.0054,
        "S16": 0.0,
        "E8": 0.0,
        "F4": 0.0,
        "Champion": 0.0,
    },
    {
        "team": "Georgia",
        "region": "Midwest",
        "seed": 8,
        "R32": 0.58,
        "S16": 0.0385,
        "E8": 0.0109,
        "F4": 0.0018,
        "Champion": 0.0,
    },
    {
        "team": "Santa Clara",
        "region": "Midwest",
        "seed": 10,
        "R32": 0.4828,
        "S16": 0.0715,
        "E8": 0.0204,
        "F4": 0.002,
        "Champion": 0.0,
    },
]

# ── Per-region bracket (most likely outcome path) ────────────────────────────
REGIONS_DATA = {
    "East": {
        "R64": [
            {
                "a": {
                    "seed": 1,
                    "team": "Duke",
                },
                "b": {
                    "seed": 16,
                    "team": "Siena",
                },
                "winner": "Duke",
                "upset": False,
            },
            {
                "a": {
                    "seed": 8,
                    "team": "Ohio St.",
                },
                "b": {
                    "seed": 9,
                    "team": "TCU",
                },
                "winner": "Ohio St.",
                "upset": False,
            },
            {
                "a": {
                    "seed": 5,
                    "team": "St. John's",
                },
                "b": {
                    "seed": 12,
                    "team": "Northern Iowa",
                },
                "winner": "St. John's",
                "upset": False,
            },
            {
                "a": {
                    "seed": 4,
                    "team": "Kansas",
                },
                "b": {
                    "seed": 13,
                    "team": "Cal Baptist",
                },
                "winner": "Kansas",
                "upset": False,
            },
            {
                "a": {
                    "seed": 6,
                    "team": "Louisville",
                },
                "b": {
                    "seed": 11,
                    "team": "South Florida",
                },
                "winner": "Louisville",
                "upset": False,
            },
            {
                "a": {
                    "seed": 3,
                    "team": "Michigan St.",
                },
                "b": {
                    "seed": 14,
                    "team": "North Dakota St.",
                },
                "winner": "Michigan St.",
                "upset": False,
            },
            {
                "a": {
                    "seed": 7,
                    "team": "UCLA",
                },
                "b": {
                    "seed": 10,
                    "team": "UCF",
                },
                "winner": "UCLA",
                "upset": False,
            },
            {
                "a": {
                    "seed": 2,
                    "team": "Connecticut",
                },
                "b": {
                    "seed": 15,
                    "team": "Furman",
                },
                "winner": "Connecticut",
                "upset": False,
            },
        ],
        "R32": [
            {
                "a": {
                    "seed": 1,
                    "team": "Duke",
                },
                "b": {
                    "seed": 8,
                    "team": "Ohio St.",
                },
                "winner": "Duke",
                "upset": False,
            },
            {
                "a": {
                    "seed": 5,
                    "team": "St. John's",
                },
                "b": {
                    "seed": 4,
                    "team": "Kansas",
                },
                "winner": "St. John's",
                "upset": True,
            },
            {
                "a": {
                    "seed": 6,
                    "team": "Louisville",
                },
                "b": {
                    "seed": 3,
                    "team": "Michigan St.",
                },
                "winner": "Michigan St.",
                "upset": False,
            },
            {
                "a": {
                    "seed": 7,
                    "team": "UCLA",
                },
                "b": {
                    "seed": 2,
                    "team": "Connecticut",
                },
                "winner": "Connecticut",
                "upset": False,
            },
        ],
        "S16": [
            {
                "a": {
                    "seed": 1,
                    "team": "Duke",
                },
                "b": {
                    "seed": 5,
                    "team": "St. John's",
                },
                "winner": "Duke",
                "upset": False,
            },
            {
                "a": {
                    "seed": 3,
                    "team": "Michigan St.",
                },
                "b": {
                    "seed": 2,
                    "team": "Connecticut",
                },
                "winner": "Connecticut",
                "upset": False,
            },
        ],
        "E8": [
            {
                "a": {
                    "seed": 1,
                    "team": "Duke",
                },
                "b": {
                    "seed": 2,
                    "team": "Connecticut",
                },
                "winner": "Duke",
                "upset": False,
            },
        ],
        "champion": "Duke",
    },
    "West": {
        "R64": [
            {
                "a": {
                    "seed": 1,
                    "team": "Arizona",
                },
                "b": {
                    "seed": 16,
                    "team": "LIU",
                },
                "winner": "Arizona",
                "upset": False,
            },
            {
                "a": {
                    "seed": 8,
                    "team": "Villanova",
                },
                "b": {
                    "seed": 9,
                    "team": "Utah St.",
                },
                "winner": "Utah St.",
                "upset": True,
            },
            {
                "a": {
                    "seed": 5,
                    "team": "Wisconsin",
                },
                "b": {
                    "seed": 12,
                    "team": "High Point",
                },
                "winner": "Wisconsin",
                "upset": False,
            },
            {
                "a": {
                    "seed": 4,
                    "team": "Arkansas",
                },
                "b": {
                    "seed": 13,
                    "team": "Hawaii",
                },
                "winner": "Arkansas",
                "upset": False,
            },
            {
                "a": {
                    "seed": 6,
                    "team": "BYU",
                },
                "b": {
                    "seed": 11,
                    "team": "N.C. State",
                },
                "winner": "BYU",
                "upset": False,
            },
            {
                "a": {
                    "seed": 3,
                    "team": "Gonzaga",
                },
                "b": {
                    "seed": 14,
                    "team": "Kennesaw St.",
                },
                "winner": "Gonzaga",
                "upset": False,
            },
            {
                "a": {
                    "seed": 7,
                    "team": "Miami FL",
                },
                "b": {
                    "seed": 10,
                    "team": "Missouri",
                },
                "winner": "Miami FL",
                "upset": False,
            },
            {
                "a": {
                    "seed": 2,
                    "team": "Purdue",
                },
                "b": {
                    "seed": 15,
                    "team": "Queens",
                },
                "winner": "Purdue",
                "upset": False,
            },
        ],
        "R32": [
            {
                "a": {
                    "seed": 1,
                    "team": "Arizona",
                },
                "b": {
                    "seed": 9,
                    "team": "Utah St.",
                },
                "winner": "Arizona",
                "upset": False,
            },
            {
                "a": {
                    "seed": 5,
                    "team": "Wisconsin",
                },
                "b": {
                    "seed": 4,
                    "team": "Arkansas",
                },
                "winner": "Arkansas",
                "upset": False,
            },
            {
                "a": {
                    "seed": 6,
                    "team": "BYU",
                },
                "b": {
                    "seed": 3,
                    "team": "Gonzaga",
                },
                "winner": "Gonzaga",
                "upset": False,
            },
            {
                "a": {
                    "seed": 7,
                    "team": "Miami FL",
                },
                "b": {
                    "seed": 2,
                    "team": "Purdue",
                },
                "winner": "Purdue",
                "upset": False,
            },
        ],
        "S16": [
            {
                "a": {
                    "seed": 1,
                    "team": "Arizona",
                },
                "b": {
                    "seed": 4,
                    "team": "Arkansas",
                },
                "winner": "Arizona",
                "upset": False,
            },
            {
                "a": {
                    "seed": 3,
                    "team": "Gonzaga",
                },
                "b": {
                    "seed": 2,
                    "team": "Purdue",
                },
                "winner": "Purdue",
                "upset": False,
            },
        ],
        "E8": [
            {
                "a": {
                    "seed": 1,
                    "team": "Arizona",
                },
                "b": {
                    "seed": 2,
                    "team": "Purdue",
                },
                "winner": "Arizona",
                "upset": False,
            },
        ],
        "champion": "Arizona",
    },
    "South": {
        "R64": [
            {
                "a": {
                    "seed": 1,
                    "team": "Florida",
                },
                "b": {
                    "seed": 16,
                    "team": "Lehigh",
                },
                "winner": "Florida",
                "upset": False,
            },
            {
                "a": {
                    "seed": 8,
                    "team": "Clemson",
                },
                "b": {
                    "seed": 9,
                    "team": "Iowa",
                },
                "winner": "Iowa",
                "upset": True,
            },
            {
                "a": {
                    "seed": 5,
                    "team": "Vanderbilt",
                },
                "b": {
                    "seed": 12,
                    "team": "McNeese St.",
                },
                "winner": "Vanderbilt",
                "upset": False,
            },
            {
                "a": {
                    "seed": 4,
                    "team": "Nebraska",
                },
                "b": {
                    "seed": 13,
                    "team": "Troy",
                },
                "winner": "Nebraska",
                "upset": False,
            },
            {
                "a": {
                    "seed": 6,
                    "team": "North Carolina",
                },
                "b": {
                    "seed": 11,
                    "team": "VCU",
                },
                "winner": "North Carolina",
                "upset": False,
            },
            {
                "a": {
                    "seed": 3,
                    "team": "Illinois",
                },
                "b": {
                    "seed": 14,
                    "team": "Penn",
                },
                "winner": "Illinois",
                "upset": False,
            },
            {
                "a": {
                    "seed": 7,
                    "team": "Saint Mary's",
                },
                "b": {
                    "seed": 10,
                    "team": "Texas A&M",
                },
                "winner": "Saint Mary's",
                "upset": False,
            },
            {
                "a": {
                    "seed": 2,
                    "team": "Houston",
                },
                "b": {
                    "seed": 15,
                    "team": "Idaho",
                },
                "winner": "Houston",
                "upset": False,
            },
        ],
        "R32": [
            {
                "a": {
                    "seed": 1,
                    "team": "Florida",
                },
                "b": {
                    "seed": 9,
                    "team": "Iowa",
                },
                "winner": "Florida",
                "upset": False,
            },
            {
                "a": {
                    "seed": 5,
                    "team": "Vanderbilt",
                },
                "b": {
                    "seed": 4,
                    "team": "Nebraska",
                },
                "winner": "Vanderbilt",
                "upset": True,
            },
            {
                "a": {
                    "seed": 6,
                    "team": "North Carolina",
                },
                "b": {
                    "seed": 3,
                    "team": "Illinois",
                },
                "winner": "Illinois",
                "upset": False,
            },
            {
                "a": {
                    "seed": 7,
                    "team": "Saint Mary's",
                },
                "b": {
                    "seed": 2,
                    "team": "Houston",
                },
                "winner": "Houston",
                "upset": False,
            },
        ],
        "S16": [
            {
                "a": {
                    "seed": 1,
                    "team": "Florida",
                },
                "b": {
                    "seed": 5,
                    "team": "Vanderbilt",
                },
                "winner": "Florida",
                "upset": False,
            },
            {
                "a": {
                    "seed": 3,
                    "team": "Illinois",
                },
                "b": {
                    "seed": 2,
                    "team": "Houston",
                },
                "winner": "Houston",
                "upset": False,
            },
        ],
        "E8": [
            {
                "a": {
                    "seed": 1,
                    "team": "Florida",
                },
                "b": {
                    "seed": 2,
                    "team": "Houston",
                },
                "winner": "Florida",
                "upset": False,
            },
        ],
        "champion": "Florida",
    },
    "Midwest": {
        "R64": [
            {
                "a": {
                    "seed": 1,
                    "team": "Michigan",
                },
                "b": {
                    "seed": 16,
                    "team": "UMBC",
                },
                "winner": "Michigan",
                "upset": False,
            },
            {
                "a": {
                    "seed": 8,
                    "team": "Georgia",
                },
                "b": {
                    "seed": 9,
                    "team": "Saint Louis",
                },
                "winner": "Georgia",
                "upset": False,
            },
            {
                "a": {
                    "seed": 5,
                    "team": "Texas Tech",
                },
                "b": {
                    "seed": 12,
                    "team": "Akron",
                },
                "winner": "Texas Tech",
                "upset": False,
            },
            {
                "a": {
                    "seed": 4,
                    "team": "Alabama",
                },
                "b": {
                    "seed": 13,
                    "team": "Hofstra",
                },
                "winner": "Alabama",
                "upset": False,
            },
            {
                "a": {
                    "seed": 6,
                    "team": "Tennessee",
                },
                "b": {
                    "seed": 11,
                    "team": "SMU",
                },
                "winner": "Tennessee",
                "upset": False,
            },
            {
                "a": {
                    "seed": 3,
                    "team": "Virginia",
                },
                "b": {
                    "seed": 14,
                    "team": "Wright St.",
                },
                "winner": "Virginia",
                "upset": False,
            },
            {
                "a": {
                    "seed": 7,
                    "team": "Kentucky",
                },
                "b": {
                    "seed": 10,
                    "team": "Santa Clara",
                },
                "winner": "Kentucky",
                "upset": False,
            },
            {
                "a": {
                    "seed": 2,
                    "team": "Iowa St.",
                },
                "b": {
                    "seed": 15,
                    "team": "Tennessee St.",
                },
                "winner": "Iowa St.",
                "upset": False,
            },
        ],
        "R32": [
            {
                "a": {
                    "seed": 1,
                    "team": "Michigan",
                },
                "b": {
                    "seed": 8,
                    "team": "Georgia",
                },
                "winner": "Michigan",
                "upset": False,
            },
            {
                "a": {
                    "seed": 5,
                    "team": "Texas Tech",
                },
                "b": {
                    "seed": 4,
                    "team": "Alabama",
                },
                "winner": "Texas Tech",
                "upset": True,
            },
            {
                "a": {
                    "seed": 6,
                    "team": "Tennessee",
                },
                "b": {
                    "seed": 3,
                    "team": "Virginia",
                },
                "winner": "Virginia",
                "upset": False,
            },
            {
                "a": {
                    "seed": 7,
                    "team": "Kentucky",
                },
                "b": {
                    "seed": 2,
                    "team": "Iowa St.",
                },
                "winner": "Iowa St.",
                "upset": False,
            },
        ],
        "S16": [
            {
                "a": {
                    "seed": 1,
                    "team": "Michigan",
                },
                "b": {
                    "seed": 5,
                    "team": "Texas Tech",
                },
                "winner": "Michigan",
                "upset": False,
            },
            {
                "a": {
                    "seed": 3,
                    "team": "Virginia",
                },
                "b": {
                    "seed": 2,
                    "team": "Iowa St.",
                },
                "winner": "Iowa St.",
                "upset": False,
            },
        ],
        "E8": [
            {
                "a": {
                    "seed": 1,
                    "team": "Michigan",
                },
                "b": {
                    "seed": 2,
                    "team": "Iowa St.",
                },
                "winner": "Michigan",
                "upset": False,
            },
        ],
        "champion": "Michigan",
    },
}

# ── Final Four & Championship ─────────────────────────────────────────────────
F4_DATA = [
    {
        "a": {
            "seed": 1,
            "team": "Duke",
        },
        "b": {
            "seed": 1,
            "team": "Florida",
        },
        "winner": "Duke",
    },
    {
        "a": {
            "seed": 1,
            "team": "Arizona",
        },
        "b": {
            "seed": 1,
            "team": "Michigan",
        },
        "winner": "Michigan",
    },
]

CHAMP_DATA = {
    "a": {
        "seed": 1,
        "team": "Duke",
    },
    "b": {
        "seed": 1,
        "team": "Michigan",
    },
    "winner": "Duke",
}

CHAMPION = "Duke"
